version: "3.8"
services:
  nginx:
    container_name: "nginx"
    image: nginx:1.19
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./conf.d/cart.conf:/etc/nginx/conf.d/cart.conf
      - ./conf.d/shop.conf:/etc/nginx/conf.d/shop.conf
      